files:
  deprecated_rules: etc/deprecated_rules.json
  packages: etc/packages.yml
  stack_schema_map: etc/stack-schema-map.yaml
  version_lock: etc/version.lock.json
rule_dirs:
- rules
bbr_rules_dirs:
- rules_building_block
testing:
  config: etc/test_config.yaml
