name: Import Rules to Elastic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    environment: Automation
    steps:
    - uses: actions/checkout@v4

    - name: Merge upstream
      run: |
        # "git checkout master" is unnecessary, already here by default
        echo "git pull --unshallow"
        git pull --unshallow  # this option is very important, you would get
                              # complains about unrelated histories without it.
                              # (but actions/checkout@v2 can also be instructed
                              # to fetch all git depth right from the start)

        echo "git remote add upstream https://github.com/elastic/detection-rules.git"
        git remote add upstream https://github.com/elastic/detection-rules.git
        echo "git fetch upstream main"
        git fetch upstream main

        # Neither forget the -b opt,
        # the feature/x ref is ambiguous at this stage
        # echo "git checkout main #-b feature/x origin/feature/x"
        # git checkout main #-b feature/x origin/feature/x

        echo 'git config --global user.email "you@example.com"'
        git config --global user.email "you@example.com"
        echo 'git config --global user.name "Your Name"'
        git config --global user.name "Your Name"
        
        echo "git merge --no-edit upstream/main"
        git merge --no-edit main
        echo "git push origin main"
        git push origin main --force
        
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      # run: make
      run: |
        pip install .[dev]
        pip install lib/kibana lib/kql
        pip install python-dotenv

    - name: Export Rules from Repo
      run: python -m detection_rules export-rules-from-repo -d rules/ -o exports/exported_rules.ndjson
      # env: 
      #   DR_KIBANA_URL: ${{ secrets.DR_KIBANA_URL }}
      #   DR_API_KEY: ${{ secrets.DR_API_KEY }}

    - name: Import Rules to Elastic
      run: python ./import-to-elastic.py
      env: 
        DR_KIBANA_URL: ${{ secrets.DR_KIBANA_URL }}
        DR_API_KEY: ${{ secrets.DR_API_KEY }}


