name: Import Rules to Elastic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    environment: Automation
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      # run: make
      run: |
        pip install .[dev]
        pip install lib/kibana lib/kql
        pip install python-dotenv

    - name: Export Rules from Repo
      run: python -m detection_rules export-rules-from-repo -d rules/ -o exports/exported_rules.ndjson
      env: 
        DR_KIBANA_URL: ${{ secrets.DR_KIBANA_URL }}
        DR_API_KEY: ${{ secrets.DR_API_KEY }}

    - name: Import Rules to Elastic
      run: python ./import-to-elastic.py
      env: 
        DR_KIBANA_URL: ${{ secrets.DR_KIBANA_URL }}
        DR_API_KEY: ${{ secrets.DR_API_KEY }}
